Model 0 Artifact
ihmeuw/vivarium_gates_child_iv_iron pull request #1
Opened 2022-03-10 22:10 UTC by hussain-jafari

## Model 0 Demography Artifact

### Description
- *Category*: data artifact
- *JIRA issue*: [MIC-2895](https://jira.ihme.washington.edu/browse/MIC-2895) 
- *Research reference*: [IV Iron - Children under five](https://vivarium-research.readthedocs.io/en/latest/concept_models/vivarium_iv_iron/child_model/concept_model.html)

### Verification and Testing
Created artifacts for South Asia and Sub-Saharan Africa and checked that population structure, demographic dimensions, etc looked good.

2022-03-10 22:32 UTC, albrja approved these changes

2022-03-11 00:42 UTC, rmudambi requested changes

2022-03-11 00:42 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/data/loader.py
> +    demographic_dimensions = pd.DataFrame([
Look at CIFF for how to do this.

2022-03-11 00:42 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/data/loader.py
> -def load_categorical_paf(key: str, location: str) -> pd.DataFrame:
Add this back in

2022-03-11 00:42 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/results_processing/process_results.py
> +from typing import NamedTuple, List, Dict, Union
order these alphabetically.

2022-03-11 00:42 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/tools/make_artifacts.py
> +    existing_artifacts = set([item.stem for item in Path(output_dir).iterdir()
Convert this str to path where check_for_existing is being called

2022-03-15 18:18 UTC, rmudambi approved these changes

2022-03-15 18:52 UTC, hussain-jafari commented
Model 0 Demography Artifact

    Category: data artifact
    JIRA issue: [MIC-2895](https://jira.ihme.washington.edu/browse/MIC-2895)
    Research reference: [IV Iron - Children under five](https://vivarium-research.readthedocs.io/en/latest/concept_models/vivarium_iv_iron/child_model/concept_model.html)

Verification and Testing

Created artifacts for South Asia and Sub-Saharan Africa and checked that population structure, demographic dimensions, etc looked good.

2022-03-15 18:56 UTC, merged