Model 0 Demography Implementation
ihmeuw/vivarium_gates_child_iv_iron pull request #2
Opened 2022-03-10 22:10 UTC by hussain-jafari

## Model 0 Demography Implementation

### Description
- *Category*: implementation
- *JIRA issue*: 
- *Research reference*: {IV Iron - Children under five}(https://vivarium-research.readthedocs.io/en/latest/concept_models/vivarium_iv_iron/child_model/concept_model.html)

### Verification and Testing
Ran a simulation for South Asia and checked that population and mortality looked reasonable.

2022-03-11 00:10 UTC, albrja approved these changes

2022-03-11 00:55 UTC, rmudambi requested changes

2022-03-11 00:55 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/model_specifications/south_asia.yaml
> +
only one yaml file

2022-03-11 00:55 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/model_specifications/south_asia.yaml
> +
Need Fertility Component (see CIFF)

2022-03-11 00:55 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/model_specifications/south_asia.yaml
> +        location: 'South Asia'
test this with the location key removed.

2022-03-15 18:24 UTC, rmudambi approved these changes

2022-03-15 18:24 UTC, rmudambi commented on src/vivarium_gates_child_iv_iron/model_specifications/iv_iron_child.yaml
> +        location: 'South Asia'
You can remove the location key here.

2022-03-15 18:57 UTC, merged